/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gnmi_ext.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gnmi_ext.pb-c.h"
void   gnmi_ext__extension__init
                     (GnmiExt__Extension         *message)
{
  static const GnmiExt__Extension init_value = GNMI_EXT__EXTENSION__INIT;
  *message = init_value;
}
size_t gnmi_ext__extension__get_packed_size
                     (const GnmiExt__Extension *message)
{
  assert(message->base.descriptor == &gnmi_ext__extension__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__extension__pack
                     (const GnmiExt__Extension *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__extension__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__extension__pack_to_buffer
                     (const GnmiExt__Extension *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__extension__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__Extension *
       gnmi_ext__extension__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__Extension *)
     protobuf_c_message_unpack (&gnmi_ext__extension__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__extension__free_unpacked
                     (GnmiExt__Extension *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__extension__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__registered_extension__init
                     (GnmiExt__RegisteredExtension         *message)
{
  static const GnmiExt__RegisteredExtension init_value = GNMI_EXT__REGISTERED_EXTENSION__INIT;
  *message = init_value;
}
size_t gnmi_ext__registered_extension__get_packed_size
                     (const GnmiExt__RegisteredExtension *message)
{
  assert(message->base.descriptor == &gnmi_ext__registered_extension__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__registered_extension__pack
                     (const GnmiExt__RegisteredExtension *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__registered_extension__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__registered_extension__pack_to_buffer
                     (const GnmiExt__RegisteredExtension *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__registered_extension__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__RegisteredExtension *
       gnmi_ext__registered_extension__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__RegisteredExtension *)
     protobuf_c_message_unpack (&gnmi_ext__registered_extension__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__registered_extension__free_unpacked
                     (GnmiExt__RegisteredExtension *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__registered_extension__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__master_arbitration__init
                     (GnmiExt__MasterArbitration         *message)
{
  static const GnmiExt__MasterArbitration init_value = GNMI_EXT__MASTER_ARBITRATION__INIT;
  *message = init_value;
}
size_t gnmi_ext__master_arbitration__get_packed_size
                     (const GnmiExt__MasterArbitration *message)
{
  assert(message->base.descriptor == &gnmi_ext__master_arbitration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__master_arbitration__pack
                     (const GnmiExt__MasterArbitration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__master_arbitration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__master_arbitration__pack_to_buffer
                     (const GnmiExt__MasterArbitration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__master_arbitration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__MasterArbitration *
       gnmi_ext__master_arbitration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__MasterArbitration *)
     protobuf_c_message_unpack (&gnmi_ext__master_arbitration__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__master_arbitration__free_unpacked
                     (GnmiExt__MasterArbitration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__master_arbitration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__uint128__init
                     (GnmiExt__Uint128         *message)
{
  static const GnmiExt__Uint128 init_value = GNMI_EXT__UINT128__INIT;
  *message = init_value;
}
size_t gnmi_ext__uint128__get_packed_size
                     (const GnmiExt__Uint128 *message)
{
  assert(message->base.descriptor == &gnmi_ext__uint128__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__uint128__pack
                     (const GnmiExt__Uint128 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__uint128__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__uint128__pack_to_buffer
                     (const GnmiExt__Uint128 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__uint128__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__Uint128 *
       gnmi_ext__uint128__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__Uint128 *)
     protobuf_c_message_unpack (&gnmi_ext__uint128__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__uint128__free_unpacked
                     (GnmiExt__Uint128 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__uint128__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__role__init
                     (GnmiExt__Role         *message)
{
  static const GnmiExt__Role init_value = GNMI_EXT__ROLE__INIT;
  *message = init_value;
}
size_t gnmi_ext__role__get_packed_size
                     (const GnmiExt__Role *message)
{
  assert(message->base.descriptor == &gnmi_ext__role__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__role__pack
                     (const GnmiExt__Role *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__role__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__role__pack_to_buffer
                     (const GnmiExt__Role *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__role__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__Role *
       gnmi_ext__role__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__Role *)
     protobuf_c_message_unpack (&gnmi_ext__role__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__role__free_unpacked
                     (GnmiExt__Role *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__role__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor gnmi_ext__extension__field_descriptors[2] =
{
  {
    "registered_ext",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GnmiExt__Extension, ext_case),
    offsetof(GnmiExt__Extension, registered_ext),
    &gnmi_ext__registered_extension__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "master_arbitration",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GnmiExt__Extension, ext_case),
    offsetof(GnmiExt__Extension, master_arbitration),
    &gnmi_ext__master_arbitration__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__extension__field_indices_by_name[] = {
  1,   /* field[1] = master_arbitration */
  0,   /* field[0] = registered_ext */
};
static const ProtobufCIntRange gnmi_ext__extension__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gnmi_ext__extension__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.Extension",
  "Extension",
  "GnmiExt__Extension",
  "gnmi_ext",
  sizeof(GnmiExt__Extension),
  2,
  gnmi_ext__extension__field_descriptors,
  gnmi_ext__extension__field_indices_by_name,
  1,  gnmi_ext__extension__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__extension__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__registered_extension__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__RegisteredExtension, id),
    &gnmi_ext__extension_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__RegisteredExtension, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__registered_extension__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = msg */
};
static const ProtobufCIntRange gnmi_ext__registered_extension__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gnmi_ext__registered_extension__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.RegisteredExtension",
  "RegisteredExtension",
  "GnmiExt__RegisteredExtension",
  "gnmi_ext",
  sizeof(GnmiExt__RegisteredExtension),
  2,
  gnmi_ext__registered_extension__field_descriptors,
  gnmi_ext__registered_extension__field_indices_by_name,
  1,  gnmi_ext__registered_extension__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__registered_extension__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__master_arbitration__field_descriptors[2] =
{
  {
    "role",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__MasterArbitration, role),
    &gnmi_ext__role__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "election_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__MasterArbitration, election_id),
    &gnmi_ext__uint128__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__master_arbitration__field_indices_by_name[] = {
  1,   /* field[1] = election_id */
  0,   /* field[0] = role */
};
static const ProtobufCIntRange gnmi_ext__master_arbitration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gnmi_ext__master_arbitration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.MasterArbitration",
  "MasterArbitration",
  "GnmiExt__MasterArbitration",
  "gnmi_ext",
  sizeof(GnmiExt__MasterArbitration),
  2,
  gnmi_ext__master_arbitration__field_descriptors,
  gnmi_ext__master_arbitration__field_indices_by_name,
  1,  gnmi_ext__master_arbitration__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__master_arbitration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__uint128__field_descriptors[2] =
{
  {
    "high",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__Uint128, high),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "low",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__Uint128, low),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__uint128__field_indices_by_name[] = {
  0,   /* field[0] = high */
  1,   /* field[1] = low */
};
static const ProtobufCIntRange gnmi_ext__uint128__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gnmi_ext__uint128__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.Uint128",
  "Uint128",
  "GnmiExt__Uint128",
  "gnmi_ext",
  sizeof(GnmiExt__Uint128),
  2,
  gnmi_ext__uint128__field_descriptors,
  gnmi_ext__uint128__field_indices_by_name,
  1,  gnmi_ext__uint128__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__uint128__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__role__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__Role, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__role__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange gnmi_ext__role__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor gnmi_ext__role__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.Role",
  "Role",
  "GnmiExt__Role",
  "gnmi_ext",
  sizeof(GnmiExt__Role),
  1,
  gnmi_ext__role__field_descriptors,
  gnmi_ext__role__field_indices_by_name,
  1,  gnmi_ext__role__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__role__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue gnmi_ext__extension_id__enum_values_by_number[2] =
{
  { "EID_UNSET", "GNMI_EXT__EXTENSION_ID__EID_UNSET", 0 },
  { "EID_EXPERIMENTAL", "GNMI_EXT__EXTENSION_ID__EID_EXPERIMENTAL", 999 },
};
static const ProtobufCIntRange gnmi_ext__extension_id__value_ranges[] = {
{0, 0},{999, 1},{0, 2}
};
static const ProtobufCEnumValueIndex gnmi_ext__extension_id__enum_values_by_name[2] =
{
  { "EID_EXPERIMENTAL", 1 },
  { "EID_UNSET", 0 },
};
const ProtobufCEnumDescriptor gnmi_ext__extension_id__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "gnmi_ext.ExtensionID",
  "ExtensionID",
  "GnmiExt__ExtensionID",
  "gnmi_ext",
  2,
  gnmi_ext__extension_id__enum_values_by_number,
  2,
  gnmi_ext__extension_id__enum_values_by_name,
  2,
  gnmi_ext__extension_id__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
