/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gnmi.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gnmi.pb-c.h"
void   gnmi__notification__init
                     (Gnmi__Notification         *message)
{
  static const Gnmi__Notification init_value = GNMI__NOTIFICATION__INIT;
  *message = init_value;
}
size_t gnmi__notification__get_packed_size
                     (const Gnmi__Notification *message)
{
  assert(message->base.descriptor == &gnmi__notification__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__notification__pack
                     (const Gnmi__Notification *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__notification__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__notification__pack_to_buffer
                     (const Gnmi__Notification *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__notification__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__Notification *
       gnmi__notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__Notification *)
     protobuf_c_message_unpack (&gnmi__notification__descriptor,
                                allocator, len, data);
}
void   gnmi__notification__free_unpacked
                     (Gnmi__Notification *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__notification__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__update__init
                     (Gnmi__Update         *message)
{
  static const Gnmi__Update init_value = GNMI__UPDATE__INIT;
  *message = init_value;
}
size_t gnmi__update__get_packed_size
                     (const Gnmi__Update *message)
{
  assert(message->base.descriptor == &gnmi__update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__update__pack
                     (const Gnmi__Update *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__update__pack_to_buffer
                     (const Gnmi__Update *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__Update *
       gnmi__update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__Update *)
     protobuf_c_message_unpack (&gnmi__update__descriptor,
                                allocator, len, data);
}
void   gnmi__update__free_unpacked
                     (Gnmi__Update *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__typed_value__init
                     (Gnmi__TypedValue         *message)
{
  static const Gnmi__TypedValue init_value = GNMI__TYPED_VALUE__INIT;
  *message = init_value;
}
size_t gnmi__typed_value__get_packed_size
                     (const Gnmi__TypedValue *message)
{
  assert(message->base.descriptor == &gnmi__typed_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__typed_value__pack
                     (const Gnmi__TypedValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__typed_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__typed_value__pack_to_buffer
                     (const Gnmi__TypedValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__typed_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__TypedValue *
       gnmi__typed_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__TypedValue *)
     protobuf_c_message_unpack (&gnmi__typed_value__descriptor,
                                allocator, len, data);
}
void   gnmi__typed_value__free_unpacked
                     (Gnmi__TypedValue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__typed_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__path__init
                     (Gnmi__Path         *message)
{
  static const Gnmi__Path init_value = GNMI__PATH__INIT;
  *message = init_value;
}
size_t gnmi__path__get_packed_size
                     (const Gnmi__Path *message)
{
  assert(message->base.descriptor == &gnmi__path__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__path__pack
                     (const Gnmi__Path *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__path__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__path__pack_to_buffer
                     (const Gnmi__Path *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__path__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__Path *
       gnmi__path__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__Path *)
     protobuf_c_message_unpack (&gnmi__path__descriptor,
                                allocator, len, data);
}
void   gnmi__path__free_unpacked
                     (Gnmi__Path *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__path__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__path_elem__key_entry__init
                     (Gnmi__PathElem__KeyEntry         *message)
{
  static const Gnmi__PathElem__KeyEntry init_value = GNMI__PATH_ELEM__KEY_ENTRY__INIT;
  *message = init_value;
}
void   gnmi__path_elem__init
                     (Gnmi__PathElem         *message)
{
  static const Gnmi__PathElem init_value = GNMI__PATH_ELEM__INIT;
  *message = init_value;
}
size_t gnmi__path_elem__get_packed_size
                     (const Gnmi__PathElem *message)
{
  assert(message->base.descriptor == &gnmi__path_elem__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__path_elem__pack
                     (const Gnmi__PathElem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__path_elem__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__path_elem__pack_to_buffer
                     (const Gnmi__PathElem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__path_elem__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__PathElem *
       gnmi__path_elem__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__PathElem *)
     protobuf_c_message_unpack (&gnmi__path_elem__descriptor,
                                allocator, len, data);
}
void   gnmi__path_elem__free_unpacked
                     (Gnmi__PathElem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__path_elem__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__value__init
                     (Gnmi__Value         *message)
{
  static const Gnmi__Value init_value = GNMI__VALUE__INIT;
  *message = init_value;
}
size_t gnmi__value__get_packed_size
                     (const Gnmi__Value *message)
{
  assert(message->base.descriptor == &gnmi__value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__value__pack
                     (const Gnmi__Value *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__value__pack_to_buffer
                     (const Gnmi__Value *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__Value *
       gnmi__value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__Value *)
     protobuf_c_message_unpack (&gnmi__value__descriptor,
                                allocator, len, data);
}
void   gnmi__value__free_unpacked
                     (Gnmi__Value *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__error__init
                     (Gnmi__Error         *message)
{
  static const Gnmi__Error init_value = GNMI__ERROR__INIT;
  *message = init_value;
}
size_t gnmi__error__get_packed_size
                     (const Gnmi__Error *message)
{
  assert(message->base.descriptor == &gnmi__error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__error__pack
                     (const Gnmi__Error *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__error__pack_to_buffer
                     (const Gnmi__Error *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__Error *
       gnmi__error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__Error *)
     protobuf_c_message_unpack (&gnmi__error__descriptor,
                                allocator, len, data);
}
void   gnmi__error__free_unpacked
                     (Gnmi__Error *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__decimal64__init
                     (Gnmi__Decimal64         *message)
{
  static const Gnmi__Decimal64 init_value = GNMI__DECIMAL64__INIT;
  *message = init_value;
}
size_t gnmi__decimal64__get_packed_size
                     (const Gnmi__Decimal64 *message)
{
  assert(message->base.descriptor == &gnmi__decimal64__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__decimal64__pack
                     (const Gnmi__Decimal64 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__decimal64__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__decimal64__pack_to_buffer
                     (const Gnmi__Decimal64 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__decimal64__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__Decimal64 *
       gnmi__decimal64__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__Decimal64 *)
     protobuf_c_message_unpack (&gnmi__decimal64__descriptor,
                                allocator, len, data);
}
void   gnmi__decimal64__free_unpacked
                     (Gnmi__Decimal64 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__decimal64__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__scalar_array__init
                     (Gnmi__ScalarArray         *message)
{
  static const Gnmi__ScalarArray init_value = GNMI__SCALAR_ARRAY__INIT;
  *message = init_value;
}
size_t gnmi__scalar_array__get_packed_size
                     (const Gnmi__ScalarArray *message)
{
  assert(message->base.descriptor == &gnmi__scalar_array__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__scalar_array__pack
                     (const Gnmi__ScalarArray *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__scalar_array__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__scalar_array__pack_to_buffer
                     (const Gnmi__ScalarArray *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__scalar_array__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__ScalarArray *
       gnmi__scalar_array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__ScalarArray *)
     protobuf_c_message_unpack (&gnmi__scalar_array__descriptor,
                                allocator, len, data);
}
void   gnmi__scalar_array__free_unpacked
                     (Gnmi__ScalarArray *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__scalar_array__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__subscribe_request__init
                     (Gnmi__SubscribeRequest         *message)
{
  static const Gnmi__SubscribeRequest init_value = GNMI__SUBSCRIBE_REQUEST__INIT;
  *message = init_value;
}
size_t gnmi__subscribe_request__get_packed_size
                     (const Gnmi__SubscribeRequest *message)
{
  assert(message->base.descriptor == &gnmi__subscribe_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__subscribe_request__pack
                     (const Gnmi__SubscribeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__subscribe_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__subscribe_request__pack_to_buffer
                     (const Gnmi__SubscribeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__subscribe_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__SubscribeRequest *
       gnmi__subscribe_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__SubscribeRequest *)
     protobuf_c_message_unpack (&gnmi__subscribe_request__descriptor,
                                allocator, len, data);
}
void   gnmi__subscribe_request__free_unpacked
                     (Gnmi__SubscribeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__subscribe_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__poll__init
                     (Gnmi__Poll         *message)
{
  static const Gnmi__Poll init_value = GNMI__POLL__INIT;
  *message = init_value;
}
size_t gnmi__poll__get_packed_size
                     (const Gnmi__Poll *message)
{
  assert(message->base.descriptor == &gnmi__poll__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__poll__pack
                     (const Gnmi__Poll *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__poll__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__poll__pack_to_buffer
                     (const Gnmi__Poll *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__poll__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__Poll *
       gnmi__poll__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__Poll *)
     protobuf_c_message_unpack (&gnmi__poll__descriptor,
                                allocator, len, data);
}
void   gnmi__poll__free_unpacked
                     (Gnmi__Poll *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__poll__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__subscribe_response__init
                     (Gnmi__SubscribeResponse         *message)
{
  static const Gnmi__SubscribeResponse init_value = GNMI__SUBSCRIBE_RESPONSE__INIT;
  *message = init_value;
}
size_t gnmi__subscribe_response__get_packed_size
                     (const Gnmi__SubscribeResponse *message)
{
  assert(message->base.descriptor == &gnmi__subscribe_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__subscribe_response__pack
                     (const Gnmi__SubscribeResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__subscribe_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__subscribe_response__pack_to_buffer
                     (const Gnmi__SubscribeResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__subscribe_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__SubscribeResponse *
       gnmi__subscribe_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__SubscribeResponse *)
     protobuf_c_message_unpack (&gnmi__subscribe_response__descriptor,
                                allocator, len, data);
}
void   gnmi__subscribe_response__free_unpacked
                     (Gnmi__SubscribeResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__subscribe_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__subscription_list__init
                     (Gnmi__SubscriptionList         *message)
{
  static const Gnmi__SubscriptionList init_value = GNMI__SUBSCRIPTION_LIST__INIT;
  *message = init_value;
}
size_t gnmi__subscription_list__get_packed_size
                     (const Gnmi__SubscriptionList *message)
{
  assert(message->base.descriptor == &gnmi__subscription_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__subscription_list__pack
                     (const Gnmi__SubscriptionList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__subscription_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__subscription_list__pack_to_buffer
                     (const Gnmi__SubscriptionList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__subscription_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__SubscriptionList *
       gnmi__subscription_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__SubscriptionList *)
     protobuf_c_message_unpack (&gnmi__subscription_list__descriptor,
                                allocator, len, data);
}
void   gnmi__subscription_list__free_unpacked
                     (Gnmi__SubscriptionList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__subscription_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__subscription__init
                     (Gnmi__Subscription         *message)
{
  static const Gnmi__Subscription init_value = GNMI__SUBSCRIPTION__INIT;
  *message = init_value;
}
size_t gnmi__subscription__get_packed_size
                     (const Gnmi__Subscription *message)
{
  assert(message->base.descriptor == &gnmi__subscription__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__subscription__pack
                     (const Gnmi__Subscription *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__subscription__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__subscription__pack_to_buffer
                     (const Gnmi__Subscription *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__subscription__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__Subscription *
       gnmi__subscription__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__Subscription *)
     protobuf_c_message_unpack (&gnmi__subscription__descriptor,
                                allocator, len, data);
}
void   gnmi__subscription__free_unpacked
                     (Gnmi__Subscription *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__subscription__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__qosmarking__init
                     (Gnmi__QOSMarking         *message)
{
  static const Gnmi__QOSMarking init_value = GNMI__QOSMARKING__INIT;
  *message = init_value;
}
size_t gnmi__qosmarking__get_packed_size
                     (const Gnmi__QOSMarking *message)
{
  assert(message->base.descriptor == &gnmi__qosmarking__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__qosmarking__pack
                     (const Gnmi__QOSMarking *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__qosmarking__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__qosmarking__pack_to_buffer
                     (const Gnmi__QOSMarking *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__qosmarking__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__QOSMarking *
       gnmi__qosmarking__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__QOSMarking *)
     protobuf_c_message_unpack (&gnmi__qosmarking__descriptor,
                                allocator, len, data);
}
void   gnmi__qosmarking__free_unpacked
                     (Gnmi__QOSMarking *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__qosmarking__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__alias__init
                     (Gnmi__Alias         *message)
{
  static const Gnmi__Alias init_value = GNMI__ALIAS__INIT;
  *message = init_value;
}
size_t gnmi__alias__get_packed_size
                     (const Gnmi__Alias *message)
{
  assert(message->base.descriptor == &gnmi__alias__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__alias__pack
                     (const Gnmi__Alias *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__alias__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__alias__pack_to_buffer
                     (const Gnmi__Alias *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__alias__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__Alias *
       gnmi__alias__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__Alias *)
     protobuf_c_message_unpack (&gnmi__alias__descriptor,
                                allocator, len, data);
}
void   gnmi__alias__free_unpacked
                     (Gnmi__Alias *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__alias__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__alias_list__init
                     (Gnmi__AliasList         *message)
{
  static const Gnmi__AliasList init_value = GNMI__ALIAS_LIST__INIT;
  *message = init_value;
}
size_t gnmi__alias_list__get_packed_size
                     (const Gnmi__AliasList *message)
{
  assert(message->base.descriptor == &gnmi__alias_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__alias_list__pack
                     (const Gnmi__AliasList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__alias_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__alias_list__pack_to_buffer
                     (const Gnmi__AliasList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__alias_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__AliasList *
       gnmi__alias_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__AliasList *)
     protobuf_c_message_unpack (&gnmi__alias_list__descriptor,
                                allocator, len, data);
}
void   gnmi__alias_list__free_unpacked
                     (Gnmi__AliasList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__alias_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__set_request__init
                     (Gnmi__SetRequest         *message)
{
  static const Gnmi__SetRequest init_value = GNMI__SET_REQUEST__INIT;
  *message = init_value;
}
size_t gnmi__set_request__get_packed_size
                     (const Gnmi__SetRequest *message)
{
  assert(message->base.descriptor == &gnmi__set_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__set_request__pack
                     (const Gnmi__SetRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__set_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__set_request__pack_to_buffer
                     (const Gnmi__SetRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__set_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__SetRequest *
       gnmi__set_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__SetRequest *)
     protobuf_c_message_unpack (&gnmi__set_request__descriptor,
                                allocator, len, data);
}
void   gnmi__set_request__free_unpacked
                     (Gnmi__SetRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__set_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__set_response__init
                     (Gnmi__SetResponse         *message)
{
  static const Gnmi__SetResponse init_value = GNMI__SET_RESPONSE__INIT;
  *message = init_value;
}
size_t gnmi__set_response__get_packed_size
                     (const Gnmi__SetResponse *message)
{
  assert(message->base.descriptor == &gnmi__set_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__set_response__pack
                     (const Gnmi__SetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__set_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__set_response__pack_to_buffer
                     (const Gnmi__SetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__set_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__SetResponse *
       gnmi__set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__SetResponse *)
     protobuf_c_message_unpack (&gnmi__set_response__descriptor,
                                allocator, len, data);
}
void   gnmi__set_response__free_unpacked
                     (Gnmi__SetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__set_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__update_result__init
                     (Gnmi__UpdateResult         *message)
{
  static const Gnmi__UpdateResult init_value = GNMI__UPDATE_RESULT__INIT;
  *message = init_value;
}
size_t gnmi__update_result__get_packed_size
                     (const Gnmi__UpdateResult *message)
{
  assert(message->base.descriptor == &gnmi__update_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__update_result__pack
                     (const Gnmi__UpdateResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__update_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__update_result__pack_to_buffer
                     (const Gnmi__UpdateResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__update_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__UpdateResult *
       gnmi__update_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__UpdateResult *)
     protobuf_c_message_unpack (&gnmi__update_result__descriptor,
                                allocator, len, data);
}
void   gnmi__update_result__free_unpacked
                     (Gnmi__UpdateResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__update_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__get_request__init
                     (Gnmi__GetRequest         *message)
{
  static const Gnmi__GetRequest init_value = GNMI__GET_REQUEST__INIT;
  *message = init_value;
}
size_t gnmi__get_request__get_packed_size
                     (const Gnmi__GetRequest *message)
{
  assert(message->base.descriptor == &gnmi__get_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__get_request__pack
                     (const Gnmi__GetRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__get_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__get_request__pack_to_buffer
                     (const Gnmi__GetRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__get_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__GetRequest *
       gnmi__get_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__GetRequest *)
     protobuf_c_message_unpack (&gnmi__get_request__descriptor,
                                allocator, len, data);
}
void   gnmi__get_request__free_unpacked
                     (Gnmi__GetRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__get_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__get_response__init
                     (Gnmi__GetResponse         *message)
{
  static const Gnmi__GetResponse init_value = GNMI__GET_RESPONSE__INIT;
  *message = init_value;
}
size_t gnmi__get_response__get_packed_size
                     (const Gnmi__GetResponse *message)
{
  assert(message->base.descriptor == &gnmi__get_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__get_response__pack
                     (const Gnmi__GetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__get_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__get_response__pack_to_buffer
                     (const Gnmi__GetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__get_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__GetResponse *
       gnmi__get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__GetResponse *)
     protobuf_c_message_unpack (&gnmi__get_response__descriptor,
                                allocator, len, data);
}
void   gnmi__get_response__free_unpacked
                     (Gnmi__GetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__get_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__capability_request__init
                     (Gnmi__CapabilityRequest         *message)
{
  static const Gnmi__CapabilityRequest init_value = GNMI__CAPABILITY_REQUEST__INIT;
  *message = init_value;
}
size_t gnmi__capability_request__get_packed_size
                     (const Gnmi__CapabilityRequest *message)
{
  assert(message->base.descriptor == &gnmi__capability_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__capability_request__pack
                     (const Gnmi__CapabilityRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__capability_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__capability_request__pack_to_buffer
                     (const Gnmi__CapabilityRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__capability_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__CapabilityRequest *
       gnmi__capability_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__CapabilityRequest *)
     protobuf_c_message_unpack (&gnmi__capability_request__descriptor,
                                allocator, len, data);
}
void   gnmi__capability_request__free_unpacked
                     (Gnmi__CapabilityRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__capability_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__capability_response__init
                     (Gnmi__CapabilityResponse         *message)
{
  static const Gnmi__CapabilityResponse init_value = GNMI__CAPABILITY_RESPONSE__INIT;
  *message = init_value;
}
size_t gnmi__capability_response__get_packed_size
                     (const Gnmi__CapabilityResponse *message)
{
  assert(message->base.descriptor == &gnmi__capability_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__capability_response__pack
                     (const Gnmi__CapabilityResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__capability_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__capability_response__pack_to_buffer
                     (const Gnmi__CapabilityResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__capability_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__CapabilityResponse *
       gnmi__capability_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__CapabilityResponse *)
     protobuf_c_message_unpack (&gnmi__capability_response__descriptor,
                                allocator, len, data);
}
void   gnmi__capability_response__free_unpacked
                     (Gnmi__CapabilityResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__capability_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__model_data__init
                     (Gnmi__ModelData         *message)
{
  static const Gnmi__ModelData init_value = GNMI__MODEL_DATA__INIT;
  *message = init_value;
}
size_t gnmi__model_data__get_packed_size
                     (const Gnmi__ModelData *message)
{
  assert(message->base.descriptor == &gnmi__model_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__model_data__pack
                     (const Gnmi__ModelData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__model_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__model_data__pack_to_buffer
                     (const Gnmi__ModelData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__model_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__ModelData *
       gnmi__model_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__ModelData *)
     protobuf_c_message_unpack (&gnmi__model_data__descriptor,
                                allocator, len, data);
}
void   gnmi__model_data__free_unpacked
                     (Gnmi__ModelData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__model_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor gnmi__notification__field_descriptors[6] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Notification, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prefix",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Notification, prefix),
    &gnmi__path__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alias",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Notification, alias),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__Notification, n_update),
    offsetof(Gnmi__Notification, update),
    &gnmi__update__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delete",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__Notification, n_delete_),
    offsetof(Gnmi__Notification, delete_),
    &gnmi__path__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "atomic",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Notification, atomic),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__notification__field_indices_by_name[] = {
  2,   /* field[2] = alias */
  5,   /* field[5] = atomic */
  4,   /* field[4] = delete */
  1,   /* field[1] = prefix */
  0,   /* field[0] = timestamp */
  3,   /* field[3] = update */
};
static const ProtobufCIntRange gnmi__notification__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor gnmi__notification__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.Notification",
  "Notification",
  "Gnmi__Notification",
  "gnmi",
  sizeof(Gnmi__Notification),
  6,
  gnmi__notification__field_descriptors,
  gnmi__notification__field_indices_by_name,
  1,  gnmi__notification__number_ranges,
  (ProtobufCMessageInit) gnmi__notification__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__update__field_descriptors[4] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Update, path),
    &gnmi__path__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Update, value),
    &gnmi__value__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_DEPRECATED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "val",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Update, val),
    &gnmi__typed_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duplicates",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Update, duplicates),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__update__field_indices_by_name[] = {
  3,   /* field[3] = duplicates */
  0,   /* field[0] = path */
  2,   /* field[2] = val */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange gnmi__update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor gnmi__update__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.Update",
  "Update",
  "Gnmi__Update",
  "gnmi",
  sizeof(Gnmi__Update),
  4,
  gnmi__update__field_descriptors,
  gnmi__update__field_indices_by_name,
  1,  gnmi__update__number_ranges,
  (ProtobufCMessageInit) gnmi__update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__typed_value__field_descriptors[13] =
{
  {
    "string_val",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Gnmi__TypedValue, value_case),
    offsetof(Gnmi__TypedValue, string_val),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_val",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Gnmi__TypedValue, value_case),
    offsetof(Gnmi__TypedValue, int_val),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uint_val",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Gnmi__TypedValue, value_case),
    offsetof(Gnmi__TypedValue, uint_val),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool_val",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Gnmi__TypedValue, value_case),
    offsetof(Gnmi__TypedValue, bool_val),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes_val",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Gnmi__TypedValue, value_case),
    offsetof(Gnmi__TypedValue, bytes_val),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float_val",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Gnmi__TypedValue, value_case),
    offsetof(Gnmi__TypedValue, float_val),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "decimal_val",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__TypedValue, value_case),
    offsetof(Gnmi__TypedValue, decimal_val),
    &gnmi__decimal64__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "leaflist_val",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__TypedValue, value_case),
    offsetof(Gnmi__TypedValue, leaflist_val),
    &gnmi__scalar_array__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "any_val",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__TypedValue, value_case),
    offsetof(Gnmi__TypedValue, any_val),
    &google__protobuf__any__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "json_val",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Gnmi__TypedValue, value_case),
    offsetof(Gnmi__TypedValue, json_val),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "json_ietf_val",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Gnmi__TypedValue, value_case),
    offsetof(Gnmi__TypedValue, json_ietf_val),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ascii_val",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Gnmi__TypedValue, value_case),
    offsetof(Gnmi__TypedValue, ascii_val),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto_bytes",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Gnmi__TypedValue, value_case),
    offsetof(Gnmi__TypedValue, proto_bytes),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__typed_value__field_indices_by_name[] = {
  8,   /* field[8] = any_val */
  11,   /* field[11] = ascii_val */
  3,   /* field[3] = bool_val */
  4,   /* field[4] = bytes_val */
  6,   /* field[6] = decimal_val */
  5,   /* field[5] = float_val */
  1,   /* field[1] = int_val */
  10,   /* field[10] = json_ietf_val */
  9,   /* field[9] = json_val */
  7,   /* field[7] = leaflist_val */
  12,   /* field[12] = proto_bytes */
  0,   /* field[0] = string_val */
  2,   /* field[2] = uint_val */
};
static const ProtobufCIntRange gnmi__typed_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor gnmi__typed_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.TypedValue",
  "TypedValue",
  "Gnmi__TypedValue",
  "gnmi",
  sizeof(Gnmi__TypedValue),
  13,
  gnmi__typed_value__field_descriptors,
  gnmi__typed_value__field_indices_by_name,
  1,  gnmi__typed_value__number_ranges,
  (ProtobufCMessageInit) gnmi__typed_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__path__field_descriptors[4] =
{
  {
    "element",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Gnmi__Path, n_element),
    offsetof(Gnmi__Path, element),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_DEPRECATED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "origin",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Path, origin),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "elem",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__Path, n_elem),
    offsetof(Gnmi__Path, elem),
    &gnmi__path_elem__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Path, target),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__path__field_indices_by_name[] = {
  2,   /* field[2] = elem */
  0,   /* field[0] = element */
  1,   /* field[1] = origin */
  3,   /* field[3] = target */
};
static const ProtobufCIntRange gnmi__path__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor gnmi__path__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.Path",
  "Path",
  "Gnmi__Path",
  "gnmi",
  sizeof(Gnmi__Path),
  4,
  gnmi__path__field_descriptors,
  gnmi__path__field_indices_by_name,
  1,  gnmi__path__number_ranges,
  (ProtobufCMessageInit) gnmi__path__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__path_elem__key_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gnmi__PathElem__KeyEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gnmi__PathElem__KeyEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__path_elem__key_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange gnmi__path_elem__key_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gnmi__path_elem__key_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.PathElem.KeyEntry",
  "KeyEntry",
  "Gnmi__PathElem__KeyEntry",
  "gnmi",
  sizeof(Gnmi__PathElem__KeyEntry),
  2,
  gnmi__path_elem__key_entry__field_descriptors,
  gnmi__path_elem__key_entry__field_indices_by_name,
  1,  gnmi__path_elem__key_entry__number_ranges,
  (ProtobufCMessageInit) gnmi__path_elem__key_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__path_elem__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gnmi__PathElem, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__PathElem, n_key),
    offsetof(Gnmi__PathElem, key),
    &gnmi__path_elem__key_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__path_elem__field_indices_by_name[] = {
  1,   /* field[1] = key */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange gnmi__path_elem__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gnmi__path_elem__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.PathElem",
  "PathElem",
  "Gnmi__PathElem",
  "gnmi",
  sizeof(Gnmi__PathElem),
  2,
  gnmi__path_elem__field_descriptors,
  gnmi__path_elem__field_indices_by_name,
  1,  gnmi__path_elem__number_ranges,
  (ProtobufCMessageInit) gnmi__path_elem__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__value__field_descriptors[2] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Value, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Value, type),
    &gnmi__encoding__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__value__field_indices_by_name[] = {
  1,   /* field[1] = type */
  0,   /* field[0] = value */
};
static const ProtobufCIntRange gnmi__value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gnmi__value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.Value",
  "Value",
  "Gnmi__Value",
  "gnmi",
  sizeof(Gnmi__Value),
  2,
  gnmi__value__field_descriptors,
  gnmi__value__field_indices_by_name,
  1,  gnmi__value__number_ranges,
  (ProtobufCMessageInit) gnmi__value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__error__field_descriptors[3] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Error, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Error, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Error, data),
    &google__protobuf__any__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__error__field_indices_by_name[] = {
  0,   /* field[0] = code */
  2,   /* field[2] = data */
  1,   /* field[1] = message */
};
static const ProtobufCIntRange gnmi__error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor gnmi__error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.Error",
  "Error",
  "Gnmi__Error",
  "gnmi",
  sizeof(Gnmi__Error),
  3,
  gnmi__error__field_descriptors,
  gnmi__error__field_indices_by_name,
  1,  gnmi__error__number_ranges,
  (ProtobufCMessageInit) gnmi__error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__decimal64__field_descriptors[2] =
{
  {
    "digits",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Decimal64, digits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "precision",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Decimal64, precision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__decimal64__field_indices_by_name[] = {
  0,   /* field[0] = digits */
  1,   /* field[1] = precision */
};
static const ProtobufCIntRange gnmi__decimal64__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gnmi__decimal64__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.Decimal64",
  "Decimal64",
  "Gnmi__Decimal64",
  "gnmi",
  sizeof(Gnmi__Decimal64),
  2,
  gnmi__decimal64__field_descriptors,
  gnmi__decimal64__field_indices_by_name,
  1,  gnmi__decimal64__number_ranges,
  (ProtobufCMessageInit) gnmi__decimal64__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__scalar_array__field_descriptors[1] =
{
  {
    "element",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__ScalarArray, n_element),
    offsetof(Gnmi__ScalarArray, element),
    &gnmi__typed_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__scalar_array__field_indices_by_name[] = {
  0,   /* field[0] = element */
};
static const ProtobufCIntRange gnmi__scalar_array__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor gnmi__scalar_array__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.ScalarArray",
  "ScalarArray",
  "Gnmi__ScalarArray",
  "gnmi",
  sizeof(Gnmi__ScalarArray),
  1,
  gnmi__scalar_array__field_descriptors,
  gnmi__scalar_array__field_indices_by_name,
  1,  gnmi__scalar_array__number_ranges,
  (ProtobufCMessageInit) gnmi__scalar_array__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__subscribe_request__field_descriptors[4] =
{
  {
    "subscribe",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__SubscribeRequest, request_case),
    offsetof(Gnmi__SubscribeRequest, subscribe),
    &gnmi__subscription_list__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "poll",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__SubscribeRequest, request_case),
    offsetof(Gnmi__SubscribeRequest, poll),
    &gnmi__poll__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aliases",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__SubscribeRequest, request_case),
    offsetof(Gnmi__SubscribeRequest, aliases),
    &gnmi__alias_list__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extension",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__SubscribeRequest, n_extension),
    offsetof(Gnmi__SubscribeRequest, extension),
    &gnmi_ext__extension__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__subscribe_request__field_indices_by_name[] = {
  2,   /* field[2] = aliases */
  3,   /* field[3] = extension */
  1,   /* field[1] = poll */
  0,   /* field[0] = subscribe */
};
static const ProtobufCIntRange gnmi__subscribe_request__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor gnmi__subscribe_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.SubscribeRequest",
  "SubscribeRequest",
  "Gnmi__SubscribeRequest",
  "gnmi",
  sizeof(Gnmi__SubscribeRequest),
  4,
  gnmi__subscribe_request__field_descriptors,
  gnmi__subscribe_request__field_indices_by_name,
  2,  gnmi__subscribe_request__number_ranges,
  (ProtobufCMessageInit) gnmi__subscribe_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define gnmi__poll__field_descriptors NULL
#define gnmi__poll__field_indices_by_name NULL
#define gnmi__poll__number_ranges NULL
const ProtobufCMessageDescriptor gnmi__poll__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.Poll",
  "Poll",
  "Gnmi__Poll",
  "gnmi",
  sizeof(Gnmi__Poll),
  0,
  gnmi__poll__field_descriptors,
  gnmi__poll__field_indices_by_name,
  0,  gnmi__poll__number_ranges,
  (ProtobufCMessageInit) gnmi__poll__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__subscribe_response__field_descriptors[4] =
{
  {
    "update",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__SubscribeResponse, response_case),
    offsetof(Gnmi__SubscribeResponse, update),
    &gnmi__notification__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sync_response",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Gnmi__SubscribeResponse, response_case),
    offsetof(Gnmi__SubscribeResponse, sync_response),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__SubscribeResponse, response_case),
    offsetof(Gnmi__SubscribeResponse, error),
    &gnmi__error__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_DEPRECATED | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extension",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__SubscribeResponse, n_extension),
    offsetof(Gnmi__SubscribeResponse, extension),
    &gnmi_ext__extension__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__subscribe_response__field_indices_by_name[] = {
  2,   /* field[2] = error */
  3,   /* field[3] = extension */
  1,   /* field[1] = sync_response */
  0,   /* field[0] = update */
};
static const ProtobufCIntRange gnmi__subscribe_response__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor gnmi__subscribe_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.SubscribeResponse",
  "SubscribeResponse",
  "Gnmi__SubscribeResponse",
  "gnmi",
  sizeof(Gnmi__SubscribeResponse),
  4,
  gnmi__subscribe_response__field_descriptors,
  gnmi__subscribe_response__field_indices_by_name,
  2,  gnmi__subscribe_response__number_ranges,
  (ProtobufCMessageInit) gnmi__subscribe_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue gnmi__subscription_list__mode__enum_values_by_number[3] =
{
  { "STREAM", "GNMI__SUBSCRIPTION_LIST__MODE__STREAM", 0 },
  { "ONCE", "GNMI__SUBSCRIPTION_LIST__MODE__ONCE", 1 },
  { "POLL", "GNMI__SUBSCRIPTION_LIST__MODE__POLL", 2 },
};
static const ProtobufCIntRange gnmi__subscription_list__mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex gnmi__subscription_list__mode__enum_values_by_name[3] =
{
  { "ONCE", 1 },
  { "POLL", 2 },
  { "STREAM", 0 },
};
const ProtobufCEnumDescriptor gnmi__subscription_list__mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "gnmi.SubscriptionList.Mode",
  "Mode",
  "Gnmi__SubscriptionList__Mode",
  "gnmi",
  3,
  gnmi__subscription_list__mode__enum_values_by_number,
  3,
  gnmi__subscription_list__mode__enum_values_by_name,
  1,
  gnmi__subscription_list__mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor gnmi__subscription_list__field_descriptors[9] =
{
  {
    "prefix",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__SubscriptionList, prefix),
    &gnmi__path__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subscription",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__SubscriptionList, n_subscription),
    offsetof(Gnmi__SubscriptionList, subscription),
    &gnmi__subscription__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_aliases",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Gnmi__SubscriptionList, use_aliases),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qos",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__SubscriptionList, qos),
    &gnmi__qosmarking__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Gnmi__SubscriptionList, mode),
    &gnmi__subscription_list__mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "allow_aggregation",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Gnmi__SubscriptionList, allow_aggregation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_models",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__SubscriptionList, n_use_models),
    offsetof(Gnmi__SubscriptionList, use_models),
    &gnmi__model_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encoding",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Gnmi__SubscriptionList, encoding),
    &gnmi__encoding__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "updates_only",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Gnmi__SubscriptionList, updates_only),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__subscription_list__field_indices_by_name[] = {
  5,   /* field[5] = allow_aggregation */
  7,   /* field[7] = encoding */
  4,   /* field[4] = mode */
  0,   /* field[0] = prefix */
  3,   /* field[3] = qos */
  1,   /* field[1] = subscription */
  8,   /* field[8] = updates_only */
  2,   /* field[2] = use_aliases */
  6,   /* field[6] = use_models */
};
static const ProtobufCIntRange gnmi__subscription_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor gnmi__subscription_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.SubscriptionList",
  "SubscriptionList",
  "Gnmi__SubscriptionList",
  "gnmi",
  sizeof(Gnmi__SubscriptionList),
  9,
  gnmi__subscription_list__field_descriptors,
  gnmi__subscription_list__field_indices_by_name,
  1,  gnmi__subscription_list__number_ranges,
  (ProtobufCMessageInit) gnmi__subscription_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__subscription__field_descriptors[5] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Subscription, path),
    &gnmi__path__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Subscription, mode),
    &gnmi__subscription_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sample_interval",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Subscription, sample_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "suppress_redundant",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Subscription, suppress_redundant),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heartbeat_interval",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Subscription, heartbeat_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__subscription__field_indices_by_name[] = {
  4,   /* field[4] = heartbeat_interval */
  1,   /* field[1] = mode */
  0,   /* field[0] = path */
  2,   /* field[2] = sample_interval */
  3,   /* field[3] = suppress_redundant */
};
static const ProtobufCIntRange gnmi__subscription__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor gnmi__subscription__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.Subscription",
  "Subscription",
  "Gnmi__Subscription",
  "gnmi",
  sizeof(Gnmi__Subscription),
  5,
  gnmi__subscription__field_descriptors,
  gnmi__subscription__field_indices_by_name,
  1,  gnmi__subscription__number_ranges,
  (ProtobufCMessageInit) gnmi__subscription__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__qosmarking__field_descriptors[1] =
{
  {
    "marking",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gnmi__QOSMarking, marking),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__qosmarking__field_indices_by_name[] = {
  0,   /* field[0] = marking */
};
static const ProtobufCIntRange gnmi__qosmarking__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor gnmi__qosmarking__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.QOSMarking",
  "QOSMarking",
  "Gnmi__QOSMarking",
  "gnmi",
  sizeof(Gnmi__QOSMarking),
  1,
  gnmi__qosmarking__field_descriptors,
  gnmi__qosmarking__field_indices_by_name,
  1,  gnmi__qosmarking__number_ranges,
  (ProtobufCMessageInit) gnmi__qosmarking__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__alias__field_descriptors[2] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Alias, path),
    &gnmi__path__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alias",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gnmi__Alias, alias),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__alias__field_indices_by_name[] = {
  1,   /* field[1] = alias */
  0,   /* field[0] = path */
};
static const ProtobufCIntRange gnmi__alias__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gnmi__alias__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.Alias",
  "Alias",
  "Gnmi__Alias",
  "gnmi",
  sizeof(Gnmi__Alias),
  2,
  gnmi__alias__field_descriptors,
  gnmi__alias__field_indices_by_name,
  1,  gnmi__alias__number_ranges,
  (ProtobufCMessageInit) gnmi__alias__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__alias_list__field_descriptors[1] =
{
  {
    "alias",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__AliasList, n_alias),
    offsetof(Gnmi__AliasList, alias),
    &gnmi__alias__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__alias_list__field_indices_by_name[] = {
  0,   /* field[0] = alias */
};
static const ProtobufCIntRange gnmi__alias_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor gnmi__alias_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.AliasList",
  "AliasList",
  "Gnmi__AliasList",
  "gnmi",
  sizeof(Gnmi__AliasList),
  1,
  gnmi__alias_list__field_descriptors,
  gnmi__alias_list__field_indices_by_name,
  1,  gnmi__alias_list__number_ranges,
  (ProtobufCMessageInit) gnmi__alias_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__set_request__field_descriptors[5] =
{
  {
    "prefix",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__SetRequest, prefix),
    &gnmi__path__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delete",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__SetRequest, n_delete_),
    offsetof(Gnmi__SetRequest, delete_),
    &gnmi__path__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "replace",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__SetRequest, n_replace),
    offsetof(Gnmi__SetRequest, replace),
    &gnmi__update__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__SetRequest, n_update),
    offsetof(Gnmi__SetRequest, update),
    &gnmi__update__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extension",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__SetRequest, n_extension),
    offsetof(Gnmi__SetRequest, extension),
    &gnmi_ext__extension__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__set_request__field_indices_by_name[] = {
  1,   /* field[1] = delete */
  4,   /* field[4] = extension */
  0,   /* field[0] = prefix */
  2,   /* field[2] = replace */
  3,   /* field[3] = update */
};
static const ProtobufCIntRange gnmi__set_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor gnmi__set_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.SetRequest",
  "SetRequest",
  "Gnmi__SetRequest",
  "gnmi",
  sizeof(Gnmi__SetRequest),
  5,
  gnmi__set_request__field_descriptors,
  gnmi__set_request__field_indices_by_name,
  1,  gnmi__set_request__number_ranges,
  (ProtobufCMessageInit) gnmi__set_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__set_response__field_descriptors[5] =
{
  {
    "prefix",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__SetResponse, prefix),
    &gnmi__path__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__SetResponse, n_response),
    offsetof(Gnmi__SetResponse, response),
    &gnmi__update_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__SetResponse, message),
    &gnmi__error__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_DEPRECATED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Gnmi__SetResponse, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extension",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__SetResponse, n_extension),
    offsetof(Gnmi__SetResponse, extension),
    &gnmi_ext__extension__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__set_response__field_indices_by_name[] = {
  4,   /* field[4] = extension */
  2,   /* field[2] = message */
  0,   /* field[0] = prefix */
  1,   /* field[1] = response */
  3,   /* field[3] = timestamp */
};
static const ProtobufCIntRange gnmi__set_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor gnmi__set_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.SetResponse",
  "SetResponse",
  "Gnmi__SetResponse",
  "gnmi",
  sizeof(Gnmi__SetResponse),
  5,
  gnmi__set_response__field_descriptors,
  gnmi__set_response__field_indices_by_name,
  1,  gnmi__set_response__number_ranges,
  (ProtobufCMessageInit) gnmi__set_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue gnmi__update_result__operation__enum_values_by_number[4] =
{
  { "INVALID", "GNMI__UPDATE_RESULT__OPERATION__INVALID", 0 },
  { "DELETE", "GNMI__UPDATE_RESULT__OPERATION__DELETE", 1 },
  { "REPLACE", "GNMI__UPDATE_RESULT__OPERATION__REPLACE", 2 },
  { "UPDATE", "GNMI__UPDATE_RESULT__OPERATION__UPDATE", 3 },
};
static const ProtobufCIntRange gnmi__update_result__operation__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex gnmi__update_result__operation__enum_values_by_name[4] =
{
  { "DELETE", 1 },
  { "INVALID", 0 },
  { "REPLACE", 2 },
  { "UPDATE", 3 },
};
const ProtobufCEnumDescriptor gnmi__update_result__operation__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "gnmi.UpdateResult.Operation",
  "Operation",
  "Gnmi__UpdateResult__Operation",
  "gnmi",
  4,
  gnmi__update_result__operation__enum_values_by_number,
  4,
  gnmi__update_result__operation__enum_values_by_name,
  1,
  gnmi__update_result__operation__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor gnmi__update_result__field_descriptors[4] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Gnmi__UpdateResult, timestamp),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_DEPRECATED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__UpdateResult, path),
    &gnmi__path__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__UpdateResult, message),
    &gnmi__error__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_DEPRECATED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "op",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Gnmi__UpdateResult, op),
    &gnmi__update_result__operation__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__update_result__field_indices_by_name[] = {
  2,   /* field[2] = message */
  3,   /* field[3] = op */
  1,   /* field[1] = path */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange gnmi__update_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor gnmi__update_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.UpdateResult",
  "UpdateResult",
  "Gnmi__UpdateResult",
  "gnmi",
  sizeof(Gnmi__UpdateResult),
  4,
  gnmi__update_result__field_descriptors,
  gnmi__update_result__field_indices_by_name,
  1,  gnmi__update_result__number_ranges,
  (ProtobufCMessageInit) gnmi__update_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue gnmi__get_request__data_type__enum_values_by_number[4] =
{
  { "ALL", "GNMI__GET_REQUEST__DATA_TYPE__ALL", 0 },
  { "CONFIG", "GNMI__GET_REQUEST__DATA_TYPE__CONFIG", 1 },
  { "STATE", "GNMI__GET_REQUEST__DATA_TYPE__STATE", 2 },
  { "OPERATIONAL", "GNMI__GET_REQUEST__DATA_TYPE__OPERATIONAL", 3 },
};
static const ProtobufCIntRange gnmi__get_request__data_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex gnmi__get_request__data_type__enum_values_by_name[4] =
{
  { "ALL", 0 },
  { "CONFIG", 1 },
  { "OPERATIONAL", 3 },
  { "STATE", 2 },
};
const ProtobufCEnumDescriptor gnmi__get_request__data_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "gnmi.GetRequest.DataType",
  "DataType",
  "Gnmi__GetRequest__DataType",
  "gnmi",
  4,
  gnmi__get_request__data_type__enum_values_by_number,
  4,
  gnmi__get_request__data_type__enum_values_by_name,
  1,
  gnmi__get_request__data_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor gnmi__get_request__field_descriptors[6] =
{
  {
    "prefix",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__GetRequest, prefix),
    &gnmi__path__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__GetRequest, n_path),
    offsetof(Gnmi__GetRequest, path),
    &gnmi__path__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Gnmi__GetRequest, type),
    &gnmi__get_request__data_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encoding",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Gnmi__GetRequest, encoding),
    &gnmi__encoding__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_models",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__GetRequest, n_use_models),
    offsetof(Gnmi__GetRequest, use_models),
    &gnmi__model_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extension",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__GetRequest, n_extension),
    offsetof(Gnmi__GetRequest, extension),
    &gnmi_ext__extension__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__get_request__field_indices_by_name[] = {
  3,   /* field[3] = encoding */
  5,   /* field[5] = extension */
  1,   /* field[1] = path */
  0,   /* field[0] = prefix */
  2,   /* field[2] = type */
  4,   /* field[4] = use_models */
};
static const ProtobufCIntRange gnmi__get_request__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 3 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor gnmi__get_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.GetRequest",
  "GetRequest",
  "Gnmi__GetRequest",
  "gnmi",
  sizeof(Gnmi__GetRequest),
  6,
  gnmi__get_request__field_descriptors,
  gnmi__get_request__field_indices_by_name,
  2,  gnmi__get_request__number_ranges,
  (ProtobufCMessageInit) gnmi__get_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__get_response__field_descriptors[3] =
{
  {
    "notification",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__GetResponse, n_notification),
    offsetof(Gnmi__GetResponse, notification),
    &gnmi__notification__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gnmi__GetResponse, error),
    &gnmi__error__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_DEPRECATED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extension",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__GetResponse, n_extension),
    offsetof(Gnmi__GetResponse, extension),
    &gnmi_ext__extension__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__get_response__field_indices_by_name[] = {
  1,   /* field[1] = error */
  2,   /* field[2] = extension */
  0,   /* field[0] = notification */
};
static const ProtobufCIntRange gnmi__get_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor gnmi__get_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.GetResponse",
  "GetResponse",
  "Gnmi__GetResponse",
  "gnmi",
  sizeof(Gnmi__GetResponse),
  3,
  gnmi__get_response__field_descriptors,
  gnmi__get_response__field_indices_by_name,
  1,  gnmi__get_response__number_ranges,
  (ProtobufCMessageInit) gnmi__get_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__capability_request__field_descriptors[1] =
{
  {
    "extension",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__CapabilityRequest, n_extension),
    offsetof(Gnmi__CapabilityRequest, extension),
    &gnmi_ext__extension__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__capability_request__field_indices_by_name[] = {
  0,   /* field[0] = extension */
};
static const ProtobufCIntRange gnmi__capability_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor gnmi__capability_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.CapabilityRequest",
  "CapabilityRequest",
  "Gnmi__CapabilityRequest",
  "gnmi",
  sizeof(Gnmi__CapabilityRequest),
  1,
  gnmi__capability_request__field_descriptors,
  gnmi__capability_request__field_indices_by_name,
  1,  gnmi__capability_request__number_ranges,
  (ProtobufCMessageInit) gnmi__capability_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__capability_response__field_descriptors[4] =
{
  {
    "supported_models",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__CapabilityResponse, n_supported_models),
    offsetof(Gnmi__CapabilityResponse, supported_models),
    &gnmi__model_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supported_encodings",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Gnmi__CapabilityResponse, n_supported_encodings),
    offsetof(Gnmi__CapabilityResponse, supported_encodings),
    &gnmi__encoding__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gNMI_version",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gnmi__CapabilityResponse, gnmi_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extension",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gnmi__CapabilityResponse, n_extension),
    offsetof(Gnmi__CapabilityResponse, extension),
    &gnmi_ext__extension__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__capability_response__field_indices_by_name[] = {
  3,   /* field[3] = extension */
  2,   /* field[2] = gNMI_version */
  1,   /* field[1] = supported_encodings */
  0,   /* field[0] = supported_models */
};
static const ProtobufCIntRange gnmi__capability_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor gnmi__capability_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.CapabilityResponse",
  "CapabilityResponse",
  "Gnmi__CapabilityResponse",
  "gnmi",
  sizeof(Gnmi__CapabilityResponse),
  4,
  gnmi__capability_response__field_descriptors,
  gnmi__capability_response__field_indices_by_name,
  1,  gnmi__capability_response__number_ranges,
  (ProtobufCMessageInit) gnmi__capability_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi__model_data__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gnmi__ModelData, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "organization",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gnmi__ModelData, organization),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gnmi__ModelData, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__model_data__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = organization */
  2,   /* field[2] = version */
};
static const ProtobufCIntRange gnmi__model_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor gnmi__model_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.ModelData",
  "ModelData",
  "Gnmi__ModelData",
  "gnmi",
  sizeof(Gnmi__ModelData),
  3,
  gnmi__model_data__field_descriptors,
  gnmi__model_data__field_indices_by_name,
  1,  gnmi__model_data__number_ranges,
  (ProtobufCMessageInit) gnmi__model_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue gnmi__encoding__enum_values_by_number[5] =
{
  { "JSON", "GNMI__ENCODING__JSON", 0 },
  { "BYTES", "GNMI__ENCODING__BYTES", 1 },
  { "PROTO", "GNMI__ENCODING__PROTO", 2 },
  { "ASCII", "GNMI__ENCODING__ASCII", 3 },
  { "JSON_IETF", "GNMI__ENCODING__JSON_IETF", 4 },
};
static const ProtobufCIntRange gnmi__encoding__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex gnmi__encoding__enum_values_by_name[5] =
{
  { "ASCII", 3 },
  { "BYTES", 1 },
  { "JSON", 0 },
  { "JSON_IETF", 4 },
  { "PROTO", 2 },
};
const ProtobufCEnumDescriptor gnmi__encoding__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "gnmi.Encoding",
  "Encoding",
  "Gnmi__Encoding",
  "gnmi",
  5,
  gnmi__encoding__enum_values_by_number,
  5,
  gnmi__encoding__enum_values_by_name,
  1,
  gnmi__encoding__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue gnmi__subscription_mode__enum_values_by_number[3] =
{
  { "TARGET_DEFINED", "GNMI__SUBSCRIPTION_MODE__TARGET_DEFINED", 0 },
  { "ON_CHANGE", "GNMI__SUBSCRIPTION_MODE__ON_CHANGE", 1 },
  { "SAMPLE", "GNMI__SUBSCRIPTION_MODE__SAMPLE", 2 },
};
static const ProtobufCIntRange gnmi__subscription_mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex gnmi__subscription_mode__enum_values_by_name[3] =
{
  { "ON_CHANGE", 1 },
  { "SAMPLE", 2 },
  { "TARGET_DEFINED", 0 },
};
const ProtobufCEnumDescriptor gnmi__subscription_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "gnmi.SubscriptionMode",
  "SubscriptionMode",
  "Gnmi__SubscriptionMode",
  "gnmi",
  3,
  gnmi__subscription_mode__enum_values_by_number,
  3,
  gnmi__subscription_mode__enum_values_by_name,
  1,
  gnmi__subscription_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCMethodDescriptor gnmi__g_nmi__method_descriptors[4] =
{
  { "Capabilities", &gnmi__capability_request__descriptor, &gnmi__capability_response__descriptor },
  { "Get", &gnmi__get_request__descriptor, &gnmi__get_response__descriptor },
  { "Set", &gnmi__set_request__descriptor, &gnmi__set_response__descriptor },
  { "Subscribe", &gnmi__subscribe_request__descriptor, &gnmi__subscribe_response__descriptor },
};
const unsigned gnmi__g_nmi__method_indices_by_name[] = {
  0,        /* Capabilities */
  1,        /* Get */
  2,        /* Set */
  3         /* Subscribe */
};
const ProtobufCServiceDescriptor gnmi__g_nmi__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "gnmi.gNMI",
  "gNMI",
  "Gnmi__GNMI",
  "gnmi",
  4,
  gnmi__g_nmi__method_descriptors,
  gnmi__g_nmi__method_indices_by_name
};
void gnmi__g_nmi__capabilities(ProtobufCService *service,
                               const Gnmi__CapabilityRequest *input,
                               Gnmi__CapabilityResponse_Closure closure,
                               void *closure_data)
{
  assert(service->descriptor == &gnmi__g_nmi__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void gnmi__g_nmi__get(ProtobufCService *service,
                      const Gnmi__GetRequest *input,
                      Gnmi__GetResponse_Closure closure,
                      void *closure_data)
{
  assert(service->descriptor == &gnmi__g_nmi__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void gnmi__g_nmi__set(ProtobufCService *service,
                      const Gnmi__SetRequest *input,
                      Gnmi__SetResponse_Closure closure,
                      void *closure_data)
{
  assert(service->descriptor == &gnmi__g_nmi__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void gnmi__g_nmi__subscribe(ProtobufCService *service,
                            const Gnmi__SubscribeRequest *input,
                            Gnmi__SubscribeResponse_Closure closure,
                            void *closure_data)
{
  assert(service->descriptor == &gnmi__g_nmi__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void gnmi__g_nmi__init (Gnmi__GNMI_Service *service,
                        Gnmi__GNMI_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &gnmi__g_nmi__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
